# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# This workflow will also lint Shell Scripts for [style, info, warnings, errors] with a single version of ShellCheck
# For more info see: https://github.com/marketplace/actions/shell-linter

name: Python application

on:
  push:
    branches: [ master, production ]
  pull_request:
    branches: [ master, production ]
 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Set up Python 3.8
        uses: actions/setup-python@v1
        with: 
          python-version: 3.8
      - 
        name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - 
        name: Lint with flake8
        run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  
  lint_shell_scripts: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout code
        uses: actions/checkout@v1
      - 
        name: Run Shellcheck
        uses: azohra/shell-linter@v0.4.0